# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'     #官方仓库地址
source 'https://github.com/bloodspasm/Pods.git'     #私有仓库地址

target 'CocoaFRPDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CocoaFRPDemo
  pod 'CocoaFRP'

end
